### ISSUE TITLE
Introduce docker enablement files

### ISSUE THREAD

**Issue by evshvarov** [bdeboe/isc-sql-utils#1]
To provide the way of easy collaboration

**Comment by bdeboe** [comment]
Thanks, but I'm not as much a fan of having a docker-compose in there just for the heck of it. This is a utility you'd want to use in your existing environment (made easy thanks to ZPM), but it's not very useful in its own docker image (which requires upkeep to stick with recent IRIS versions). 
We've had this conversation before :-), so maybe I'm overlooking some handy separate-branch-for-automated-testing option

**Comment by evshvarov** [comment]
That's fine! Docker-compose and friends are more to ease the collaboration of other people. Not sure how you perform the collaboration to other open-source IRIS libs but with docker-compose is much easier. Though I don't like very much a set of almost the same files in each and every repo.

**Comment by bdeboe** [comment]
addressed by PR #5
